services:
  mongo:
    image: mongo
    container_name: crud-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node-products-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/crud-app
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes: 
      - .:/usr/src/app
    command: npm start

volumes:
  mongo-data:
